// api/containers — container lifecycle. Numbers come only from the shared
// allocator; QR tokens are permanent and never regenerated by moves, renames,
// renumbering, type changes, or archiving.

import { createClientFromRequest } from "npm:@base44/sdk";
import { serveActions, badRequest, deny } from "../../../shared/http.ts";
import { requireMember, requireLocationCap, accessibleLocationIds } from "../../../shared/authz.ts";
import { logActivity } from "../../../shared/audit.ts";
import { assertWithinLimit } from "../../../shared/entitlements.ts";
import { allocateNumber, reserveSpecificNumber, formatNumber } from "../../../shared/numbering.ts";
import { newQrToken, QR_LINK_BASE } from "../../../shared/tokens.ts";
import { buildSearchText } from "../../../shared/searchtext.ts";

const CONTAINER_TYPES = [
  "bin", "tote", "box", "crate", "bag", "drawer", "cabinet", "trunk", "case", "bucket", "file_box", "custom",
] as const;

function publicContainer(c: Record<string, any>, location?: Record<string, any> | null) {
  return {
    id: c.id,
    location_id: c.location_id,
    location_path: location?.path_text,
    number: c.number ?? null,
    number_display: c.number ? formatNumber(c.number) : null,
    pending_number: !!c.pending_number,
    container_type: c.container_type,
    custom_type_label: c.custom_type_label,
    title: c.title,
    description: c.description,
    category: c.category,
    tags: c.tags ?? [],
    size_capacity: c.size_capacity,
    container_color: c.container_color,
    lid_color: c.lid_color,
    notes: c.notes,
    label_status: c.label_status ?? "not_printed",
    archived: !!c.archived,
    qr_link: c.qr_token ? `${QR_LINK_BASE}${c.qr_token}` : null,
    created_date: c.created_date,
    updated_date: c.updated_date,
  };
}

function refreshSearchText(c: Record<string, any>): string {
  return buildSearchText([
    c.title, c.description, c.category, c.tags, c.notes,
    c.number ? formatNumber(c.number) : null, c.custom_type_label,
  ]);
}

const EDITABLE_FIELDS = [
  "title", "description", "category", "tags", "size_capacity",
  "container_color", "lid_color", "notes", "custom_type_label", "custom",
] as const;

serveActions({
  create_container: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const location = await requireLocationCap(ctx, payload.location_id, "create_inventory");
    if (location.archived) throw badRequest("Cannot create containers in an archived location");

    const title = typeof payload.title === "string" ? payload.title.trim().slice(0, 200) : "";
    if (!title) throw badRequest("Title is required");
    const type = (payload.container_type as string) || "bin";
    if (!CONTAINER_TYPES.includes(type as any)) throw badRequest("Invalid container type");
    await assertWithinLimit(ctx.sr, ctx.workspace.id, "containers");

    const container = await ctx.sr.entities.Container.create({
      workspace_id: ctx.workspace.id,
      location_id: location.id,
      qr_token: newQrToken(),
      container_type: type,
      custom_type_label: type === "custom" ? String(payload.custom_type_label ?? "").slice(0, 60) : undefined,
      title,
      description: typeof payload.description === "string" ? payload.description : undefined,
      category: typeof payload.category === "string" ? payload.category : undefined,
      tags: Array.isArray(payload.tags) ? payload.tags.filter((t) => typeof t === "string").slice(0, 50) : [],
      notes: typeof payload.notes === "string" ? payload.notes : undefined,
      label_status: "not_printed",
      archived: false,
      pending_number: true,
      client_uuid: typeof payload.client_uuid === "string" ? payload.client_uuid : undefined,
      updated_by_user_id: ctx.user.id,
    });
    const number = await allocateNumber(ctx.sr, ctx.workspace.id, container.id);
    const updated = await ctx.sr.entities.Container.update(container.id, {
      number,
      number_display: formatNumber(number),
      pending_number: false,
      search_text: refreshSearchText({ ...container, number }),
    });
    await logActivity(ctx.sr, {
      workspace_id: ctx.workspace.id, actor: ctx.user, action: "container.created",
      target_type: "container", target_id: container.id,
      target_label: `${formatNumber(number)} ${title}`,
    });
    return { container: publicContainer(updated, location) };
  },

  get_container: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const container = await ctx.sr.entities.Container.get(payload.container_id).catch(() => null);
    if (!container || container.workspace_id !== ctx.workspace.id) throw deny();
    const location = await requireLocationCap(ctx, container.location_id, "view");
    return { container: publicContainer(container, location) };
  },

  list_containers: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const accessible = await accessibleLocationIds(ctx);

    const query: Record<string, unknown> = { workspace_id: ctx.workspace.id };
    if (typeof payload.location_id === "string" && payload.location_id) {
      await requireLocationCap(ctx, payload.location_id, "view");
      query.location_id = payload.location_id;
    }
    // Archived containers appear only through the explicit filter.
    query.archived = payload.archived_filter === true;

    const containers = await ctx.sr.entities.Container.filter(query, "-updated_date", 500);
    const visible = accessible === null
      ? containers
      : containers.filter((c: any) => accessible.has(c.location_id));
    const locations = await ctx.sr.entities.Location.filter({ workspace_id: ctx.workspace.id });
    const locById = new Map(locations.map((l: any) => [l.id, l]));
    return { containers: visible.map((c: any) => publicContainer(c, locById.get(c.location_id))) };
  },

  update_container: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const container = await ctx.sr.entities.Container.get(payload.container_id).catch(() => null);
    if (!container || container.workspace_id !== ctx.workspace.id) throw deny();
    await requireLocationCap(ctx, container.location_id, "edit_inventory");
    if (container.archived) throw badRequest("Restore the container before editing");

    const patch: Record<string, unknown> = { updated_by_user_id: ctx.user.id };
    for (const field of EDITABLE_FIELDS) {
      if (field in (payload.patch as object ?? {})) patch[field] = (payload.patch as any)[field];
    }
    if (typeof (payload.patch as any)?.container_type === "string") {
      const t = (payload.patch as any).container_type;
      if (!CONTAINER_TYPES.includes(t)) throw badRequest("Invalid container type");
      patch.container_type = t;
    }
    if (typeof (payload.patch as any)?.label_status === "string") {
      const s = (payload.patch as any).label_status;
      if (!["not_printed", "queued", "printed"].includes(s)) throw badRequest("Invalid label status");
      patch.label_status = s;
    }
    const merged = { ...container, ...patch };
    patch.search_text = refreshSearchText(merged);
    const updated = await ctx.sr.entities.Container.update(container.id, patch);
    await logActivity(ctx.sr, {
      workspace_id: ctx.workspace.id, actor: ctx.user, action: "container.updated",
      target_type: "container", target_id: container.id, target_label: updated.title,
    });
    const location = await ctx.sr.entities.Location.get(updated.location_id).catch(() => null);
    return { container: publicContainer(updated, location) };
  },

  /** Admin-only renumber; QR token and identity are untouched, old number stays retired. */
  renumber_container: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id, "edit_numbers");
    const container = await ctx.sr.entities.Container.get(payload.container_id).catch(() => null);
    if (!container || container.workspace_id !== ctx.workspace.id) throw deny();
    const newNumber = Number(payload.new_number);
    await reserveSpecificNumber(ctx.sr, ctx.workspace.id, container.id, newNumber);
    const updated = await ctx.sr.entities.Container.update(container.id, {
      number: newNumber,
      number_display: formatNumber(newNumber),
      search_text: refreshSearchText({ ...container, number: newNumber }),
      updated_by_user_id: ctx.user.id,
    });
    await logActivity(ctx.sr, {
      workspace_id: ctx.workspace.id, actor: ctx.user, action: "container.renumbered",
      target_type: "container", target_id: container.id,
      metadata: { from: container.number, to: newNumber },
    });
    return { container: publicContainer(updated) };
  },

  /** Moving needs move_inventory at BOTH ends; destination permissions apply immediately. */
  move_container: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const container = await ctx.sr.entities.Container.get(payload.container_id).catch(() => null);
    if (!container || container.workspace_id !== ctx.workspace.id) throw deny();
    await requireLocationCap(ctx, container.location_id, "move_inventory");
    const destination = await requireLocationCap(ctx, payload.new_location_id, "move_inventory");
    if (destination.archived) throw badRequest("Cannot move into an archived location");

    await ctx.sr.entities.Container.update(container.id, {
      location_id: destination.id, updated_by_user_id: ctx.user.id,
    });
    const items = await ctx.sr.entities.Item.filter({ workspace_id: ctx.workspace.id, container_id: container.id });
    for (const item of items) {
      await ctx.sr.entities.Item.update(item.id, { location_id: destination.id });
    }
    await logActivity(ctx.sr, {
      workspace_id: ctx.workspace.id, actor: ctx.user, action: "container.moved",
      target_type: "container", target_id: container.id,
      metadata: { from_location: container.location_id, to_location: destination.id },
    });
    return {
      moved: true,
      access_warning: ctx.workspace.workspace_type !== "household"
        ? "Access now follows the destination location's permissions."
        : null,
    };
  },

  set_archived: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const container = await ctx.sr.entities.Container.get(payload.container_id).catch(() => null);
    if (!container || container.workspace_id !== ctx.workspace.id) throw deny();
    await requireLocationCap(ctx, container.location_id, "archive_inventory");
    const archived = payload.archived === true;
    await ctx.sr.entities.Container.update(container.id, {
      archived,
      archived_at: archived ? new Date().toISOString() : null,
      updated_by_user_id: ctx.user.id,
    });
    await logActivity(ctx.sr, {
      workspace_id: ctx.workspace.id, actor: ctx.user,
      action: archived ? "container.archived" : "container.restored",
      target_type: "container", target_id: container.id, target_label: container.title,
    });
    return { archived };
  },

  /** Damaged-label fallback: find a container by its display number. */
  lookup_by_number: async (payload, req) => {
    const base44 = createClientFromRequest(req);
    const ctx = await requireMember(base44, payload.workspace_id);
    const number = Number(payload.number);
    if (!Number.isInteger(number) || number < 1) throw deny();
    const matches = await ctx.sr.entities.Container.filter({ workspace_id: ctx.workspace.id, number });
    const container = matches[0];
    if (!container) throw deny();
    // Same generic denial whether the number is unused or out of scope.
    const location = await requireLocationCap(ctx, container.location_id, "view").catch(() => { throw deny(); });
    return { container: publicContainer(container, location) };
  },
});
